name: Build & Release Angular App

on:
  push:
    tags:
      - "v*.*.*" # Runs on versioned tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: |
          cd modern-swissunihockey
          npm ci

      - name: Build Angular application
        run: |
          cd modern-swissunihockey
          npm run build

      - name: Zip the output folder
        run: |
          tar -czvf wp-swiss-uniho.tar.gz wp-swiss-uniho/

      - name: Debug Environment Variables
        run: env | grep GITHUB
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUB_API_URL: "https://api.github.com" # Override Gitea API URL
          GITHUB_SERVER_URL: "https://github.com"
          GITHUB_ACTOR: "S-Schindi"
          GITHUB_REPOSITORY_OWNER: "S-Schindi"
          GITHUB_REPOSITORY: "S-Schindi/swissunihockey-webcomponents"

      # - name: Create GitHub release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     files: wp-swiss-uniho.tar.gz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      #     GITHUB_API_URL: "https://api.github.com" # Override Gitea API URL
      #     GITHUB_SERVER_URL: "https://github.com"
      #     GITHUB_ACTOR: "S-Schindi"
      #     GITHUB_REPOSITORY_OWNER: "S-Schindi"
      #     GITHUB_REPOSITORY: "S-Schindi/swissunihockey-webcomponents"

      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
                && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Create GitHub release using gh CLI
        run: |
          env -i bash -c '
            export PATH="$PATH"
            export GITHUB_API_URL="https://api.github.com"
            export GITHUB_SERVER_URL="https://github.com"
            export GITHUB_TOKEN="${{ secrets.GITHUBTOKEN }}"

            gh release create "${{ github.ref_name }}" wp-swiss-uniho.tar.gz \
              --repo S-Schindi/swissunihockey-webcomponents \
              --title "Release ${{ github.ref_name }}" \
              --notes "Automated release by Gitea Actions"
          '
